### PR TITLE
73163

### PR DESCRIPTION
**Pull request by djhaynes**

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
@djhaynes Was there an error that caused you to need all of the `to_s` calls?

**Comment by djhaynes** [comment]
Yeah, @aaronlippold reported #125. The to_s method returns "" which will cause the test to fail rather than getting the undefined method error.

**Comment by trevor-vaughan** [comment]
Ugh, that's unfortunate :-|

**Comment by aaronlippold** [comment]
Is that input required? If so we can add a required true field to the yml

**Comment by djhaynes** [comment]
@aaronlippold can you clarify your comment? I am not quite sure what you are talking about. Thanks.

**Pull request merged**
