### PR TITLE
Deprecated tests & Adding missing tests from RHEL7 STIG v2r4

### PR DESCRIPTION
**Pull request by HackerShark**
Merging in PR #114 and #113 

Pulled in latest updates from Master of Simp. 
Rebased depracatedTests with Simp master. 
Merged updates. 
Resolved all merge conflicts.
Cleaned up controls.
Made various fixes.

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
@aaronlippold Looks like we're still having an issue, do you know what might be causing this?

https://travis-ci.org/github/simp/inspec-profile-disa_stig-el7/jobs/658905934#L1472

**Comment by aaronlippold** [comment]
It looks like a parsing issue of the outcoming JSON file. The only change
they made to the JSON structure was when they added the waivers data.

**Comment by trevor-vaughan** [comment]
I ran the test without these updates on a different repo and didn't have any issues so I think it's something related to this change but there's not really enough to go on.

**Comment by trevor-vaughan** [comment]
Oh, this is an issue with running the `inspec` command. Nothing has touched the JSON yet.

**Comment by trevor-vaughan** [comment]
I see that inspec is now running but we're not getting a report. Can you see if there is any valid output coming from this new data set?

**Comment by trevor-vaughan** [comment]
There seems to still be something wrong:

```
[root@el7 inspec]# inspec exec inspec_profiles/CentOS-7-disa_stig/CentOS-7-disa_stig --chef-license accept
Unable to parse inspec.yml: line 437, did not find expected key while parsing a block mapping
```

**Comment by trevor-vaughan** [comment]
This identified a bug in `simp-beaker-helpers` which was not providing adequate reporting when inspec failed.

Fixed in https://github.com/simp/rubygem-simp-beaker-helpers/pull/121 and will be released soon

**Comment by op-ct** [comment]
For anyone tracking this PR: simp/rubygem-simp-beaker-helpers#121 was released on [April 07][0].

However, we've recently migrated our org's Travis CI from travis-ci.org to travis-ci.com, so restarting the previous Travis PR checks  to pick up the new gems won't clear the failed travis-ci.org checks (and we can't get rid of them). 

As a workaround, we can push up a trivial change to the PR, which will prompt all CI PR checks rerun on the new commit from scratch.

[0]: https://github.com/simp/rubygem-simp-beaker-helpers/compare/1.18.3...1.18.4

**Comment by trevor-vaughan** [comment]
Closing. Maintenance has been moved to https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline

**Pull request closed without merging**
